# -*- coding: utf-8 -*-
"""Day1 - Band_name_generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13r-7C9mpIBYTS8rne6XGLGk3LrCwRtQO
"""

#DAY1
#Learned about print(), input() and String Manipulation.
print("Welcome to Band Name Generator")

genre = input("Which genre of songs do you play?\n")

instrument = input("Which instrument you like to play? \n")

print ("Name of your band could be: "+genre+" "+instrument)